# Generated by Django 5.2.5 on 2026-05-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_campaign_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='completed', max_length=20),
        ),
    ]
