# Generated by Django 5.2.5 on 2026-05-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_campaign_campaign_name_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='number_list',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
