# Generated by Django 5.2.5 on 2026-05-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_campaign_number_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='complete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='file_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='campaign',
            name='nonwa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='rejected',
            field=models.IntegerField(default=0),
        ),
    ]
