# Generated by Django 5.2.5 on 2026-07-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_create_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('failed_to_send', 'Failed To Send'), ('cancelled', 'Cancelled')], default='completed', max_length=20),
        ),
    ]
