# Generated by Django 5.2.5 on 2026-08-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_campaign_call_label_campaign_call_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='dp_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
